### ISSUE TITLE
This should probably be pulled back into a private repo....

### ISSUE THREAD

**Issue by saschaben** [ilios/ilios.github.io#1]

**Comment by stopfstedt** [comment]
why

**Comment by Trott** [comment]
The only reason I can come up with is that we don't want ilios.github.io competing with the iliosproject.org so we'd want to keep this private/unpublished until we actually replace the official site. My response to that reason would be: Just add a `robots.txt` so it doesn't show up in search engines and give it a CNAME file and DNS record like `beta.iliosproject.org`. The way I see it, for Ilios, a private repo is a code smell. We *want* people to know what's being worked on.

**Comment by stopfstedt** [comment]
Thanks Rich.

**Comment by saschaben** [comment]
@Trott is correct: this isn't code, and it isn't collaborative: it's a (hopefully) replacement for the public facing (eg marketing) site. therefore not really a "public" facing work in progress. We really DON'T want people to be poking around in a half-baked marketing website.

**Comment by stopfstedt** [comment]
@saschaben  ^ collaboration is already happening. I agree with "should be private" in a sense of "the beta site shouldn't be picked up by search engines".
