### ISSUE TITLE
Add link to installation instructions

### ISSUE THREAD

**Issue by jrjohnson** [ilios/ilios.github.io#10]
@saschaben Should we link to the ilios2 instructions until we have a final 3.0 release?

**Comment by saschaben** [comment]
That's probably a good idea -- a link to the i2 instructions and a comment and link viz. i3.

**Comment by saschaben** [comment]
N.B. Remember here and as a best practice to add the code for rendering an external link target (`{:target="_blank"}` for markdown or `target="_blank"` attribute for html hrefs)

**Comment by saschaben** [comment]
3.0.0 now released.

MOOT
