### ISSUE TITLE
What is left to do?

### ISSUE THREAD

**Issue by jrjohnson** [ilios/ilios.github.io#7]
@saschaben can you scan the existing website and see what things still need to be ported before we can go live with this jekyl site?  If you create a bunch of individual tickets we can start picking them off over the next few weeks.

**Comment by saschaben** [comment]
@dartajax is going to provide a spreadsheet of the delta for the 2 sites; we will determine final navigation and info inclusion from that list.

**Comment by jrjohnson** [comment]
- [ ] Minimum technical requirements
- [ ] Link to github wiki
- [ ] Sign up for the mailing list
- [ ] Get info for the demo
- [ ] Update posts from WP site
- [ ] Typo in Contact US (capital S)
- [ ] Banner on home page
- [ ] logo in place of home link at top right corner
- [ ] Direct link to installation instructions (as big spinning GET ILIOS)

**Comment by jrjohnson** [comment]
Created new issues for remaining tasks.
